name: Push on commit

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Send Push Notification
      uses: techulus/push-github-action@1.0.0
      env:
        API_KEY: 50f819a2-5659-487f-9b84-9cbbb9dbcefb
        MESSAGE: "There is a new commit!"
